### ISSUE TITLE
Feature: unit testing and model-based testing

### ISSUE THREAD

**Issue by konnov** [apalache-mc/apalache#787]
This is a meta-issue for the work on unit testing for TLA+ and support for model-based testing. All relevant issues are labelled with [FMBT](https://github.com/informalsystems/apalache/labels/FMBT).

 - [x] Enumeration of counterexamples: #833, #827, #542
 - [ ] Support for VIEW in TLC configs: #851
 - [ ] First prototype for unit testing: #810, [RFC006](https://apalache.informal.systems/docs/adr/006rfc-unit-testing.html), and #191
   - [x] Check action invariants: #801 
   - [x] Check trace invariants: #822

**Comment by konnov** [comment]
Shall we spin off #730 into its own meta-issue? I guess, it will be a lot of work.

**Comment by konnov** [comment]
No customer
